version: '1.0'

services:
  backend:
    build: 
      context: ./backend/
      dockerfile: Dockerfile
    container_name: backendoop
    ports:
      - "3001:3001"
    depends_on:
      - database
    environment:
      - DB_HOST=databaseoop
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=admin1234
      - DB_NAME=mydb
      - APP_PORT=3001
      - JWT_SECRET=secret

  frontend:
    build: 
      context: ./frontend/
      dockerfile: Dockerfile
    container_name: frontendoop
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"

  database:
    image: postgres:latest
    container_name: databaseoop
    volumes:
      - ./database:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: postgresadminoop
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin1234
    ports:
      - "5050:80"
